Modify css
CodeStash-KGP/set_proxy pull request #34
Opened 2019-02-02 13:05 UTC by baymac

## Problem

_What problem are you trying to solve?_

The previous website needed some UI changes and code refractory. For displaying the code images were used, now code UI has been implemented.
## Solution

_How did you solve the problem?_

I have modified the existing design with different colors, separate stylesheets for the article segment, added link for social media handles, used js for slider function, removed images and replaced it with code blocks.

## Before & After Screenshots

**BEFORE**:
![screenshot from 2019-02-02 18-31-42](https://user-images.githubusercontent.com/23079344/52164545-19add880-2719-11e9-94bf-4cde46450e42.png)

**AFTER**:
![screenshot from 2019-02-02 18-31-17](https://user-images.githubusercontent.com/23079344/52164546-1ca8c900-2719-11e9-9900-72436bbdb02b.png)

## Other changes (e.g. bug fixes, UI tweaks, small refactors)

2019-02-02 13:13 UTC, baymac commented
You can check the website hosted on my heroku account. Link: https://proxy-master-baymac.herokuapp.com/

2019-02-03 00:50 UTC, baymac commented
After changing colors and instructions format. It looks like this.
![screenshot from 2019-02-03 06-18-55](https://user-images.githubusercontent.com/23079344/52171043-b3a66d00-277b-11e9-8bb7-e11a29ce9344.png)

2019-02-03 03:32 UTC, thealphadollar requested changes
Please add the following links in the social media buttons.

2019-02-03 03:32 UTC, thealphadollar commented on templates/index.html
> +      <a href=""><img src="../static/img/facebook.svg" alt=""></a>
https://www.facebook.com/metakgp/

2019-02-03 03:32 UTC, thealphadollar commented on templates/index.html
> +      <a href=""><img src="../static/img/twitter.svg" alt=""></a>
https://twitter.com/metakgp

2019-02-03 03:32 UTC, thealphadollar commented on templates/index.html
> +      <a href=""><img src="../static/img/github.svg" alt=""></a>
https://github.com/metakgp

2019-02-03 10:50 UTC, baymac commented on templates/index.html
> +      <a href=""><img src="../static/img/github.svg" alt=""></a>
I have added them.

2019-02-03 12:35 UTC, thealphadollar approved these changes
LGTM!

2019-02-03 12:35 UTC, merged

2019-02-03 12:35 UTC, thealphadollar commented
Thank you @baymac for the PR.